# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(resolve:APP_SECRET)%'
    #csrf_protection: true
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: false
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

    http_client:
        max_host_connections: 10
        default_options:
            retry_failed:
                enabled: true
                max_retries: 6
                delay: 1000
                multiplier: 4
        scoped_clients:
            client:
                base_uri: https://api.bigcommerce.com/stores/
                

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
