zenstruck_schedule:
    timezone: UTC
    http_client: http_client
    mailer:
        service: mailer # required
        default_to: tuckersfurniture@gmail.com # optional (exclude if defined in code)
        default_from: tuckersfurniture@gmail.com # exclude only if a "global from" is defined for your application
        subject_prefix: "Cron Job" # optional

    tasks:
        -   task: app:customer-refresh Customers ?Tenant=sm6apxdkrh
            frequency: '*/10 * * * *' # every 10 minutes
            without_overlapping:
                enabled: true
                ttl: 600

        -   task: app:vendor-update Vendors ?Tenant=sm6apxdkrh
            frequency: '*/2 * * * *' # every hour
            without_overlapping:
                enabled: true
                ttl: 3600

        -   task: app:master-update
            frequency: '*/15 * * * *' # every 6 minutes
            without_overlapping:
                enabled: true
                ttl: 900

        -   task: app:package-update Products Packages ?Tenant=sm6apxdkrh
            frequency: '*/20 * * * *' # every 20 minutes
            without_overlapping:
                enabled: true
                ttl: 1200
                
        -   task: app:bc-brand-update
            frequency: '*/30 * * * *' # every 30 minutes
            without_overlapping:
                enabled: true
                ttl: 1800

        -   task: app:bc-item-sync
            frequency: '*/20 * * * *' # every 20 minutes
            without_overlapping:
                enabled: true
                ttl: 1200

        -   task: app:bc-package-sync
            frequency: '*/20 * * * *' # every 20 minutes
            without_overlapping:
                enabled: true
                ttl: 1200

        -   task: app:bc-item-new
            frequency: '*/10 * * * *' # every 5 minutes
            without_overlapping:
                enabled: true
                ttl: 600

        -   task: app:bc-package-new
            frequency: '*/10 * * * *' # every 5 minutes
            without_overlapping:
                enabled: true
                ttl: 600

        -   task: app:bc-item-update
            frequency: '*/25 * * * *' # every 20 minutes
            without_overlapping:
                enabled: true
                ttl: 900

        -   task: app:bc-package-update
            frequency: '*/15 * * * *' # every 20 minutes
            without_overlapping:
                enabled: true
                ttl: 900

        -   task: app:order-update
            frequency: '*/5 * * * *' # every 5 minutes
            without_overlapping:
                enabled: true
                ttl: 300

        -   task: app:send-profit-order ?Tenant=sm6apxdkrh
            frequency: '*/5 * * * *' # every 5 minutes
            without_overlapping:
                enabled: true
                ttl: 300